# ---------------------------------
# Finds module Automaton 
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE_MODULE_AUTOMATON "Dynamically link OpenViBE module Automaton" ON)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_AUTOMATON)
	SET(OPENVIBE_MODULE_AUTOMATON_LINKING "")
	ADD_DEFINITIONS(-DAutomaton_Shared)
ELSE(DYNAMIC_LINK_OPENVIBE_MODULE_AUTOMATON)
	SET(OPENVIBE_MODULE_AUTOMATON_LINKING "-static")
	ADD_DEFINITIONS(-DAutomaton_Static)
ENDIF(DYNAMIC_LINK_OPENVIBE_MODULE_AUTOMATON)

set(PATH_OPENVIBE_MODULES_AUTOMATON "PATH_OPENVIBE_MODULES_AUTOMATON-NOTFOUND")
set(SRC_DIR ${OV_BASE_DIR}/modules/automaton/include)

FIND_PATH(PATH_OPENVIBE_MODULES_AUTOMATON automaton/defines.h PATHS ${SRC_DIR} NO_DEFAULT_PATH)
IF(PATH_OPENVIBE_MODULES_AUTOMATON)
	MESSAGE(STATUS "  Found OpenViBE module Automaton...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE_MODULES_AUTOMATON}/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME} openvibe-module-automaton${OPENVIBE_MODULE_AUTOMATON_LINKING})

	ADD_DEFINITIONS(-DTARGET_HAS_Automaton)
ELSE(PATH_OPENVIBE_MODULES_AUTOMATON)
	MESSAGE(STATUS "  FAILED to find OpenViBE module Automaton...")
ENDIF(PATH_OPENVIBE_MODULES_AUTOMATON)
