# ---------------------------------
# Finds Eigen headers
#
# Adds include path
# ---------------------------------

IF(WIN32)
	SET(PATH_EIGEN "PATH_EIGEN-NOTFOUND")
	FIND_PATH(PATH_EIGEN Eigen/Eigen PATHS ${LIST_DEPENDENCIES_PATH} PATH_SUFFIXES eigen NO_DEFAULT_PATH)
	IF(PATH_EIGEN)
		SET(EIGEN_FOUND TRUE)
		SET(EIGEN_INCLUDE_DIRS ${PATH_EIGEN})
		SET(EIGEN_CFLAGS "")
		#SET(EIGEN_LIBRARIES_RELEASE EIGEN)
		#SET(EIGEN_LIBRARIES_DEBUG EIGENd)
		#SET(EIGEN_LIBRARY_DIRS ${PATH_EIGEN}/lib )
	ENDIF()
ENDIF()

IF(UNIX)
	INCLUDE("FindPkgConfig")
	pkg_check_modules(EIGEN eigen3)
ENDIF()

IF(EIGEN_FOUND)
	debug_message("  Found eigen3...")
	INCLUDE_DIRECTORIES("${EIGEN_INCLUDE_DIRS}")
	ADD_DEFINITIONS(${EIGEN_CFLAGS})

	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyEIGEN)
ELSE()
	MESSAGE(WARNING "  FAILED to find eigen3...")
ENDIF()

